# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ['5432:5432']
        env:
          POSTGRES_DB: events_system_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.3.1'
      - run: gem install bundler
      - run: bundle install
      - run: cp config/database.yml.ci config/database.yml
      - run: bin/rails db:create db:schema:load
      - run: bin/rails test
